### PR TITLE
Patch mic.mm to fix crash on iOS10 beta 3.

### PR DESCRIPTION
**Pull request by jchenevey**
This merge fixes an issue wherein the microphone being accessed was causing a privacy violation crash on iOS 10 beta 3.

### CODE REVIEW

**Comment by quentinlesceller** [comment]
Thank you so much. Working great now.

**Comment by WilliamLCobb** [comment]
Thank you for this!

**Comment by jchenevey** [comment]
No problem! Cheers to my first merged pull request on GitHub! :)

**Comment by Voussoiir** [comment]
@WilliamLCobb closing lid function has been already added? How is it work?

**Comment by aw8** [comment]
@WilliamLCobb @jchenevey This patch allows games to run on iOS 10 beta 3, but microphone support doesn't seem to work anymore. (Also, no dialogue appears asking for permission to use the microphone.)

It seems like the problem might be similar to the one solved here: https://forums.developer.apple.com/thread/51985

When I add a microphone usage description to the plist entry and remove the changes made in this commit, microphone support seems to work on iOS 10b3 (as far as I can tell).

**Pull request merged**
